export gpugc_checked=false
export gpugc_mode=analyze
./run-dacapo-all.sh FastAdaptiveGPU_x86_64-linux 2>&1 | tee log-analysis.log
#this script takes all the refdist_*_*.dat files generated by the run and sums them into a master report
python combine-refdist.py > refdist_dacapo.dat
